1	PRINT*,"ENTER NEW INTERVAL:"
	READ*,A,B
	IF(F(A).EQ.0) THEN 
	PRINT*,A," IS ROOT"
	ENDIF 
	IF(F(B).EQ.0) THEN 
	PRINT*,B , " IS ROOT"
	ENDIF
	IF(F(A)*F(B).GT.0) THEN 
	PRINT*,"INVALID INTERVAL"
	GOTO 1
	ENDIF
	ITER = 0
2	IF(F(A)*F(B) .LT.0) THEN
	C = (F(B)*A - F(A)*B)/(F(B) - F(A))
	ITER = ITER + 1
	PRINT*,"THE ROOT AFTER " ,ITER , "ITERATION IS " ,C

	IF(ABS(F(C)) .LT.10E-6) THEN 
	GOTO 3
	
	ENDIF
	ENDIF
	
	IF(F(C).EQ.0) THEN
	PRINT*,"THE ROOT IS : " ,C
	ENDIF
	IF(F(A)*F(C) .LT.0) THEN
		B =C
		GOTO 2
		ENDIF 
	IF(F(B)*F(C) .LT.0) THEN
		A =C
		GOTO 2
		ENDIF
3	PRINT*,"THE FINAL ROOT AFTER " , ITER , "ITERATIONS ARE " , C
	STOP
	END
	FUNCTION F(X)
	F =  X*X*X -7
		RETURN
	END


