	DIMENSION A(100,100) , X(100)
	PRINT*,"ENTER THE ORDER OF MATRIX"
	READ*,N
	PRINT*,"ENTER THE ELEMENT OF MATRIX"
	READ*,((A(I,J) ,J = 1 , N+1) , I = 1 , N)
	!CHECK FOR UPPER TRIANGULAR
	DO J = 1 , N-1
	DO I = J +1 , N
	T = A(I,J)/A(J,J)
	DO K = 1 , N+1
	A(I,K) = A(I,K) - A(J,K)*T
	ENDDO
	ENDDO
	ENDDO
	X(N) = A(N,N+1)/A(N,N)
	DO I = N ,1 ,-1
	SOL = A(I,N+1)
	DO J = I+1 , N
	SOL = SOL - A(I,J)*X(J)
	ITER = ITER+1
	DO P = 1 ,N
	PRINT*,"SOLUTION OF VARIABLE",P,"AFTER",ITER,"TH BACK SUBST:",X(P)
	ENDDO
	ENDDO
	X(I) = SOL/A(I,I)
	ENDDO
	DO K = 1 , N
	PRINT*,"THE SOLUTION OF VARIABLE",K,
	1"AFTER ALL BACK SUBSTITUTION IS:",X(K)
	
	ENDDO
	STOP
	END
