	!GAUSS SIEDAL
	DIMENSION A(100,100) , B(100) , C(100) , D(100) !D IS DUMMY MATRIX
	PRINT*,"ENTER ORDER OF MATRIX"
	READ*,N
1	PRINT*,"ENTER COEFFICIENT OF EACH VARIABLE:"
	
	READ*,((A(I,J) , J = 1 ,N) , I = 1, N)
	!CHECK FOR DIAGONAL DOMINANCE
	T = 0
	S = 0
	DO I = 1 , N
	DO J = 1 , N
	IF(J.EQ.I) THEN
	T = T + A(I,J)
	ELSE 
	S = S + A(I,J)
	ENDIF
	ENDDO
	IF(T.LT.S) THEN 
	PRINT*,"SYSTEM IS NOT DIAGONALLY DOMINANT"
	GOTO 1
	ENDIF
	ENDDO
	PRINT*,"THE ENTERED MATRIX IS CORRECT"
	PRINT*,"ENTER B MATRIX"
	READ*,(B(I) , I = 1 , N)
	PRINT*,"ENTER INITIAL GUESSES"
	READ*,(C(I) , I = 1 , N)
	ITER = 0
	DO
	ITER = ITER +1
	DO I = 1 , N
	SUM = 0
	DO J = 1 ,N
	IF(I.GT.J) THEN
	SUM = SUM + A(I,J)*D(J)
	ELSEIF(I.LT.J) THEN
	SUM = SUM + A(I,J)*C(J)
	ENDIF
	ENDDO
	D(I) = (B(I) - SUM)/A(I,I)
	PRINT*,"SOLUTION AFTER",ITER,"ITERATION= " ,D(1:N) 
	ENDDO
	IF(ALL(ABS(C-D).LT.10E-4)) EXIT
	C = D
	ENDDO
	PRINT*,"THE SOLUTION AFTER",ITER,"ITERATION IS:",D(1:N)
	STOP 
	END
