	!LAGRANGE INTERPOLATING
	DIMENSION X(50),Y(50)
	PRINT*,'ENTER THE NUMBER OF POINT'
	READ*,N
	PRINT*,'ENTER THE POINT'
	READ*,(X(I),I=1,N)
	PRINT*,'ENTER THE VALUE OF FUNCTION'
	READ*,(Y(I),I=1,N)
	PRINT*,'ENTER THE POINT EHER VALUE REQUIRED'
	READ*,A

	S=0
	DO I=1,N
	P=1
	D=1
	DO J=1,N
	IF(I.NE.J) THEN
	P=P*(A-X(J))
	D=D*(X(I)-X(J))
	END IF
	END DO
	T=P*Y(I)/D
	S=S+T
	END DO

	PRINT*,'ANSWER IS',S
	STOP
	END
