!MODIFIED EULER METHOD
	DIMENSION X(100) , Y(100)
	PRINT*,"ENTER INITIAL POINT"
	READ*,X0,Y0
	PRINT*,"ENTER STEP SIZE"
	READ*,H
	PRINT*,"ENTER POINT AT WHICH YOU WANT VALUE"
	READ*,A
	L = (A/H)
	ITER = 0
	DO I = 1 , L 
	Y(I) = Y0 + H*F(X0 , Y0)
	Q = Y(I)

2	P = Y0+H*(0.5)*(F(X0,Y0)+F(X0+H,Q))
 	 ITER  = ITER +1
	PRINT*,"THE VALUE AFTER",ITER , "ITERATION IS",P
	IF(ABS(P-Q).LT.10E-4) THEN
	PRINT*,"THE FINAL VALUE OF Y(",I*H,")=" ,P
	GOTO 1
	ELSE
	Q = P 
	GOTO 2
	ENDIF
1	X0 = X0 +H
	Y0 = P
	ENDDO
	STOP
	END
	FUNCTION F(X,Y)
	F = (X-Y)/2
	RETURN
	END
